### ISSUE TITLE
Page doesnt produce a url list 

### ISSUE THREAD

**Issue by theghostyced** [the-urlist/frontend-vue-typescript#4]
## Description Of Problem

After adding the required fields i.e a title, description of the links and the list of links, the page fails to create the link for me and instead throws this error in the console.

## Hardware

- Firefox
- Mac OS Mojave

![Screenshot 2019-10-12 at 9 33 45 AM](https://user-images.githubusercontent.com/28215750/66698167-7bc0d380-ecd3-11e9-90b1-b117885ae1b5.png)

**Comment by burkeholland** [comment]
We have an issue where the function application dies on occasion. We still aren't sure why this is. When that happens, the /api URLs return an HTML 504. This is interpreted by axios as XML which it cannot parse and the error there is what you get. 

Basically, the API was down when you tried to create your list. ☹️
