### ISSUE TITLE
Generate unique url strings

### ISSUE THREAD

**Issue by theghostyced** [the-urlist/frontend-vue-typescript#5]
## Description of Problem

Currently, the given title passed by a user when generating a url list is what is being used to generate the url.

e.g `Title` = `ced`, `URL` = `https://theurlist.com/ced`

## Expected Result

I expected that a unqiue string be attached to the title being sent in by the user.

i.e `Title` = `ced`, `URL` = `https://theurlist.com/ced-942jda9`. 

This way, we have little or no conflict in the generation of a URL. 😁

**Comment by burkeholland** [comment]
The application does this if you leave the title blank. It will just give you an auto-generated URL. Maybe we need to clarify that.
